config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    member do
        get "like", to: "restaurants#upvote"
        get "dislike", to: "restaurants#downvote"
    end 	
  	resources :items
  	resources :comments
  end
  resources :categories 
  resources :users

  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	is_impressionable
	acts_as_votable
	has_many :items
	has_many :comments
	has_many :categorizations
	has_many :categories, through: :categorizations
	geocoded_by :address        #從address欄位取出地址
	after_validation :geocode   #將取出的地址自動轉為經緯度分別存在 latitude、longitude 欄位
	validates_presence_of :name, :imageURL # Can't empty.
	has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/ 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :if_search_restaurant
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]
  impressionist :actions=>[:show,:index]

  # GET /restaurants
  # GET /restaurants.json
  def index
    if params[:search]
      @restaurants = Restaurant.where('name LIKE ? OR address LIKE ? OR phone1 LIKE ? OR phone2 LIKE ? OR note LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    elsif params[:category].blank?
      @restaurants = Restaurant.all.order("RANDOM()")
    else
      @categories = Category.all
      @restaurants = []
      (Restaurant.all.order("RANDOM()")).each do |restaurant|
        if restaurant.category_ids.include?(@categories.find_by_name(params[:category]).id)
          @restaurants.push(restaurant)
        end
      end
    end

    respond_to do |format|
      format.html
      format.html.phone
      format.html.tablet
    end       
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
        marker.lat restaurant.latitude
        marker.lng restaurant.longitude
        marker.infowindow restaurant.address
    end     
    @visitorCount = Restaurant.find(params[:id])
    impressionist(@visitorCount)     
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
      @restaurant.upvote_by current_user
      redirect_to :back
  end

  def downvote
      @restaurant.downvote_by current_user
      redirect_to :back       
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:website, :imageURL, :menu_url, :image, :name, :address, :phone1, :phone2, :note, :vegetarian, :category_ids => [] )
    end

    def if_search_restaurant
      if params[:search]
        @restaurants = Restaurant.where('name LIKE ? OR address LIKE ? OR phone1 LIKE ? OR phone2 LIKE ? OR note LIKE ?', "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
        render :index
      end
    end  
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
	#https://makandracards.com/makandra/29353-tel_to-rails-helper-for-linking-phone-numbers
	def tel_to(text)
	  groups = text.to_s.scan(/(?:^\+)?\d+/)
	  link_to text, "tel:#{groups.join '-'}"
	end	
end

app/views/restaurants/_form.html.haml
= simple_form_for @restaurant, html:{multipart: true} do |f|
    - if @restaurant.errors.any?
        %p
            = pluralize(@restaurant.errors.count, "error")
            prohibited this restaurant from being saved
        %ul
            - restaurant.errors.full_messages.each do |message|
                %li= message

    .panel-body
        = f.input :name, input_html: { class: 'form-control' }
        = f.input :imageURL, input_html: { class: 'form-control' }
        = f.input :menu_url, input_html: { class: 'form-control' }
        = f.input :address, input_html: { class: 'form-control' }
        = f.input :phone1, input_html: { class: 'form-control' }
        = f.input :phone2, input_html: { class: 'form-control' } 
        = f.input :website, input_html: { class: 'form-control' }      
        = f.input :note, input_html: { class: 'form-control' }
        /= f.input :vegetarian, input_html: { class: 'form-control' }
        = f.collection_check_boxes :category_ids, Category.all, :id, :name
    = f.button :submit, class: "btn btn-primary"

app/views/restaurants/_modalQRcode.html.erb
<!-- Button trigger modal -->
<button style='width:100%;font-size: 30px' type="button" class="btn btn-default fa fa-qrcode" data-toggle="modal" data-target="#qrcodeModal">
  QRcode
</button>

<!-- Modal -->
<div class="modal fade" id="qrcodeModal" tabindex="-1" role="dialog" aria-labelledby="qrcodeModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title" id="exampleModalLabel">分享</h3>        
      </div>
      <div class="modal-body">
        <%= image_tag("https://scontent-tpe1-1.xx.fbcdn.net/v/t1.0-9/17190606_10207280476365257_8784016032817684205_n.jpg?oh=8eabbe7b6f51d9eb054cab2105c7a564&oe=5972ABB7", width: '100%') %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.haml
#show-box.row
	.col-md-6.col-md-offset-3
		.box
			.panel.panel-default
				%h1
					Editing Restaurant
				= render 'form', item: @item
				= link_to 'Back', @restaurant, class: "btn btn-info"

app/views/restaurants/index.html+phone.haml
#restaurants-phone.transitions-enabled
  .box-qrcode.panel
    %div.text-center= render 'restaurants/modalQRcode'
  - @restaurants.each do |restaurant|
    .box.panel
      %table{:border => "0", :valign => "top"}
        %tr
          %td
            - if restaurant.imageURL.present?
              = link_to (image_tag restaurant.imageURL , width: '100%'), restaurant
            - elsif restaurant.image.present?
              = link_to (image_tag restaurant.image.url(:small) , width: '100%'), restaurant
            - else
              = link_to restaurant.name, restaurant    
          %td.title.col{:valign => "top" ,width: '100%'}
            = link_to truncate(restaurant.name, length: 10), restaurant
            %table              
              %tr
                - if restaurant.phone1.present?
                  %h4= tel_to restaurant.phone1
                - else
                  %h4 電話未提供   
              %tr         
                - if restaurant.address.present?
                  %h5= truncate(restaurant.address, length: 16)
                - else
                  %h5 地址未提供                   
              %table{:border => "0",:style => "width:100%"}
                %tr
                  %td.h4{:style => "text-align:left;margin:10px;"}
                    = pluralize(restaurant.get_likes.size, "")
                    %i.fa.fa-thumbs-o-up{"aria-hidden" => "true"}  
                  %td.h4
                    = restaurant.comments.count
                    %i.fa.fa-commenting-o{"aria-hidden" => "true"}                     
                  %td.h6{:style => "text-align:right;color:gray;"}
                    = restaurant.impressionist_count
                    次瀏覽

app/views/restaurants/index.html.haml
#index-box
  /%div.text-center
  /  = render 'restaurants/modalQRcode'
  #restaurants.transitions-enabled.row
    - @restaurants.each do |restaurant|
      .box.panel.panel-default.col-sm-6.col-md-3
        - if restaurant.imageURL.present?
          = link_to (image_tag restaurant.imageURL , width: '100%'), restaurant
        - elsif restaurant.image.present?
          = link_to (image_tag restaurant.image.url(:small) , width: '100%'), restaurant
        - else
          = link_to restaurant.name, restaurant
        %h2{:style => "font-size:20px;"}
          = link_to truncate(restaurant.name, length: 10), restaurant
        %h4.detail
          - if restaurant.phone1.present?
            %p.h4= tel_to restaurant.phone1
          - else
            %p.h4 電話未提供
          /
            <haml_silent> if restaurant.phone2.present? </haml_silent><haml_block>
            <p><haml_loud> restaurant.phone2 </haml_loud></p>
            </haml_block>
          %h4
          %table{:style => "width:100%;margin-left:20px;margin-right:20px;"}
            %tr
              %th.h4{:style => "text-align:left;margin:10px;"}
                = pluralize(restaurant.get_likes.size, "")
                %i.fa.fa-thumbs-o-up{"aria-hidden" => "true"}              
              %th.h4{:style => "text-align:left;margin:10px;"}
                = restaurant.comments.count
                %i.fa.fa-commenting-o{"aria-hidden" => "true"}              
              %th.h6{:style => "text-align:left;color:gray;"}
                = restaurant.impressionist_count
                次瀏覽
        %h4.detail.btn-group
          = link_to "讚", like_restaurant_path(restaurant), method: :get,class: "fa fa-thumbs-o-up btn btn-default"
          = link_to "收回讚", dislike_restaurant_path(restaurant), method: :get,class:"fa fa-thumbs-o-down btn btn-default"
        - if user_signed_in?
          - if current_user.admin == true
            .dropdown
              #menu1{"data-toggle" => "dropdown"}
                %a{:href => "#", :style => "background:white;"}
                  %li.fa.fa-sort-desc.fa-2x{"aria-hidden" => "true"}
              %ul.dropdown-menu{"aria-labelledby" => "menu1", :role => "menu"}
                %li
                  = link_to 'Edit', edit_restaurant_path(restaurant)
                %li
                  = link_to  "Delete", restaurant, method: :delete, data: { confirm: "Are you sure?" }

app/views/restaurants/index.html.phone.erb
<h1>Phone page test</h1>

app/views/restaurants/new.html.haml
#show-box.row
	.col-md-6.col-md-offset-3
		.box
			.panel.panel-default
				%h1
					New Restaurant
				= render 'form', restaurant: @restaurant
				= link_to 'Back', restaurants_path, class: "btn btn-info"

app/views/restaurants/show.html.haml
#show-box.row
  /= @visitorCount.impressionist_count
  .box.panel
    .panel.panel-default
      - if @restaurant.imageURL.present?
        = link_to (image_tag @restaurant.imageURL , width: '100%'), @restaurant
      - elsif @restaurant.image.present?
        = link_to (image_tag @restaurant.image.url(:small) , width: '100%'), @restaurant
      - else
        = link_to @restaurant.name, @restaurant
      - if @restaurant.menu_url.present?
        = link_to (image_tag @restaurant.menu_url , width: '100%'), @restaurant
    .panel-body
      %h1
        = @restaurant.name
        - if @restaurant.website.present?
          = link_to '前往店家網站', @restaurant.website, class: "btn btn-warning"
      %h4{:style => "text-align:left;"}
        = pluralize(@restaurant.get_likes.size, "")
        %i.fa.fa-thumbs-o-up{"aria-hidden" => "true"}
        = @restaurant.comments.count
        %i.fa.fa-commenting-o{"aria-hidden" => "true"}
        %h4
          = @visitorCount.impressionist_count 
          次瀏覽
      %h4.detail.btn-group
        = link_to "讚", like_restaurant_path(@restaurant), method: :get,class: "fa fa-thumbs-o-up btn btn-default"
        = link_to "收回讚", dislike_restaurant_path(@restaurant), method: :get,class:"fa fa-thumbs-o-down btn btn-default"
      .detail
        %p
          = @restaurant.address
        %p
          餐廳分類：
          - @restaurant.categories.each do |category|
            = category.name
        %br/
        %p
          = tel_to @restaurant.phone1
        - if @restaurant.phone2.present?
          %p= tel_to @restaurant.phone2
        %p
          %br>/
          備註:
          %br/
          = simple_format(@restaurant.note)
      #items_wrapper
        %p
        %table.table
          %thead
            %tr
              %th Image
              %th Name
              %th Price
              %th
          %tbody
            = render @restaurant.items
        %br/
        - if user_signed_in?
          - if current_user.admin == true
            %button.btn.btn-success{"data-target" => "#myModal", "data-toggle" => "modal", :type => "button"} 新增菜色
            = render "items/modalForm"
    #comments
      %h3
        = @restaurant.comments.count
        則留言
      %table.table{:style => "word-break:break-all"}
        %thead
          %tr
            %th{:width => "100"}
            %th
            %th
        %tbody
          = render @restaurant.comments
      / <h3>Add a comment:</h3>
      = render "comments/form"
    %div
      #map{:style => "max-width:100%;height:400px"} 地圖預留
      :javascript
        handler = Gmaps.build('Google');
                    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                    markers = handler.addMarkers(#{raw @hash.to_json});
                    handler.bounds.extendWith(markers);
                    handler.fitMapToBounds();
                  });
    - if user_signed_in?
      - if current_user.admin == true
        .btn-group
          = link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-info"
          = link_to 'Delete', @restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"