config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    member do
        get "like", to: "restaurants#upvote"
        get "dislike", to: "restaurants#downvote"
    end 	
  	resources :items
  	resources :comments
  end
  resources :categories 
  resources :users

  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :restaurant
	validates_presence_of :name, :price # Can't empty. , :imageURL
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_restaurant

    def create
        @item = @restaurant.items.create(item_params)
        @item.save         
        redirect_to @restaurant
    end

    def new
        @item = Item.new
    end

    def edit
        @item = Item.find(params[:id])
    end

    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
            redirect_to @restaurant
        else
            render 'edit'
        end
    end

    def destroy
        @item = @restaurant.items.find(params[:id])
        if @item.destroy
            flash[:success] = "Restaurant item was deleted."
        else
            flash[:error] = "Restaurant item could not be deleted."
        end
        redirect_to @restaurant
    end    

    private

    def set_restaurant
        @restaurant = Restaurant.find(params[:restaurant_id])
    end

    def item_params
        params[:item].permit(:name, :price, :imageURL, :vegetarian, :note, :count, :rating, :score, :restaurant_id)
    end	
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= simple_form_for ([@restaurant, @restaurant.items.build]), html:{multipart: true} do |f|
	.panel-body
		= f.input :name, input_html: { class: 'form-control' }
		= f.input :price, input_html: { class: 'form-control' }
		= f.input :imageURL, input_html: { class: 'form-control' }
		= f.input :note, input_html: { class: 'form-control' }
		= f.input :vegetarian, input_html: { class: 'form-control' }
	= f.button :submit, class: 'btn btn-success'

app/views/items/_item.html.erb
<tr>
  <td>
      <% if item.imageURL.present? %>       
          <%= render 'items/modalItemImage', item: item %>
      <% end %>    
  </td>
  <td>
      <%= item.name %>
  </td>
  <td>
      <%= item.price %>元
  </td>
  <td>
  <% if user_signed_in? %>
      <% if current_user.admin == true %>  
          <div class="dropdown">
            <div id="menu1" data-toggle="dropdown">
              <a href="#" style="background:white;"><li class="fa fa-sort-desc fa-2x" aria-hidden="true"></li></a>
            </div>

            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
              <li>
                  <%= link_to 'Edit', edit_restaurant_item_path(@restaurant, item.id) %>
              </li>
              <li>
                  <%= link_to  "Delete", restaurant_item_path(@restaurant, item.id), method: :delete, data: { confirm: "Are you sure?" } %>
              </li>          
            </ul>
          </div>
      <% end %>
  <% end %>    
  </td>  
</tr> 

app/views/items/_modalForm.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h1 class="modal-title" id="exampleModalLabel">新增菜色</h1>        
      </div>
      <div class="modal-body">
          <%= simple_form_for ([@restaurant, @restaurant.items.build]), html:{multipart: true} do |f| %>
                <div class="panel-body">
                  <%= f.input :name, input_html: { class: 'form-control' } %>
                  <%= f.input :price, input_html: { class: 'form-control' } %>
                  <%= f.input :imageURL, input_html: { class: 'form-control' } %>
                  <%= f.input :note, input_html: { class: 'form-control' } %>
                  <%= f.input :vegetarian, input_html: { class: 'form-control' } %>
                </div>
                             
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <%= f.button :submit, class: 'btn btn-success' %>
                </div>  
          <% end %>        
      </div>

    </div>
  </div>
</div>

app/views/items/_modalItemImage.html.erb
<div type='button' style="background:white;cursor: pointer;" data-toggle="modal" data-target="#itemModal" data-name="<%= item.name %>" data-price='<%= item.price %>' data-image='<%= item.imageURL %>'><%= image_tag item.imageURL, width: '50px'%></div>

<div class="modal fade" id="itemModal" tabindex="-1" role="dialog" aria-labelledby="itemModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	        <span aria-hidden="true">&times;</span>
	      </button>
	      <h3 class="modal-title" id="itemModalLabel"></h3>                  
	    </div>
	    <div class="modal-body">
	      <img id="modal-image" width='100%'>
	    </div>
	      <h3 class="modal-footer" id="itemModalLabel"></h3> 
	  </div>
	</div>
</div>


<script>
$('#itemModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var name = button.data('name') // Extract info from data-* attributes
  var price = button.data('price') // Extract info from data-* attributes
  var imageURL = button.data('image') // Extract info from data-* attributes
  var modalImg = document.getElementById("modal-image");
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text(name)
  modal.find('.modal-footer').text(price+'元')
  modalImg.src = imageURL
})
</script>

app/views/items/edit.html.erb
<div class="row" id="show-box">
  <div class="col-md-6 col-md-offset-3">
    <div class="box">
      <div class="panel panel-default">
        <h1>
          Edit Item
        </h1>
        <div class='panel-body'>
			<%= form_for @item, :url => { :controller => 'items', :action => 'update', :id => @item } do |f| %>
			    <%= f.label :name, "Name" %>
			    <%= f.text_field :name ,class: 'form-control' %>

			    <%= f.label :price, "Price" %>
			    <%= f.text_field :price,class: 'form-control' %>

			    <%= f.label :imageURL, "Image URL" %>
			    <%= f.text_field :imageURL,class: 'form-control' %>			   

			    <%= f.label :vegetarian, "Vegetarian" %>
			    <%= f.check_box :vegetarian,class: 'form-control' %>	

			    <%= f.label :note, "Note" %>
			    <%= f.text_field :note,class: 'form-control' %>	
			    <div class="btn-group">
			    	<%= link_to 'Back', @restaurant, class: "btn btn-info" %>
			    	<%= f.submit "Update", class: "btn btn-primary" %>
			    </div>
			<% end %>        
	        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.haml
#show-box.row
	.col-md-6.col-md-offset-3
		.box
			.panel.panel-default
				%h1
					New Item
				= render 'form', item: @item
				= link_to 'Back', restaurants_path, class: "btn btn-info"