config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    member do
        get "like", to: "restaurants#upvote"
        get "dislike", to: "restaurants#downvote"
    end 	
  	resources :items
  	resources :comments
  end
  resources :categories 
  resources :users

  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :categorizations
	has_many :restaurants, through: :categorizations
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :find_category, only: [:show, :edit, :update, :destroy]

	def index
		@categories = Category.all
	end

    def show
    end

	def new
		@category = Category.new
	end

	def edit
	end

	def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to @category
        else
            render 'new'
        end		
	end

	def update
		respond_to do |format|
		  if @category.update(category_params)
		    format.html { redirect_to @category, notice: 'Category was successfully updated.' }
		    format.json { render :show, status: :ok, location: @category }
		  else
		    format.html { render :edit }
		    format.json { render json: @category.errors, status: :unprocessable_entity }
		  end
		end
	end

	def destroy
        if @category.destroy
            flash[:success] = "Category was deleted."
        else
            flash[:error] = "Category could not be deleted."
        end
        redirect_to @category		
	end

	private

    def find_category
        @category = Category.find(params[:id])
    end

	def category_params
		params.require(:category).permit(:name)
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for @category do |f|
	.panel-body
		= f.input :name
		= f.submit

app/views/categories/edit.html.haml
#show-box.row
	.col-md-6.col-md-offset-3
		.box
			.panel.panel-default
				%h1
					Edit Category

				= render 'form'
				= link_to 'Back', categories_path, class: "btn btn-info"

app/views/categories/index.html.haml
#show-box.row
	.col-md-6.col-md-offset-3
		.box
			.panel.panel-default
				.panel-body
					%h1 Category List
					- @categories.each do |category|
						%h2= category.name
						%p
							Publish at
							= category.created_at.strftime('%b %d, %Y')
							.btn-group
								= link_to "Edit", edit_category_path(category), class: "btn btn-info btn-xs"
								= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"


					= link_to "New Category", new_category_path

app/views/categories/new.html.haml
#show-box.row
	.col-md-6.col-md-offset-3
		.box
			.panel.panel-default
				%h1
					New Category

				= render 'form'
				= link_to 'Back', categories_path, class: "btn btn-info"

app/views/categories/show.html.erb
<div class="row" id="show-box">
  <div class="col-md-6 col-md-offset-3">
    <div class="box">
      	<div class="panel panel-default">
      		<div class="panel-body">
      			<h1><%= @category.name %></h1>
      			<p>Publish at
				        <%= @category.created_at.strftime('%b %d, %Y') %></p>

      			<%= link_to 'Back', categories_path, class: "btn btn-info" %>				
      		</div>
		</div>
    </div>
  </div>
</div>