config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    member do
        get "like", to: "restaurants#upvote"
        get "dislike", to: "restaurants#downvote"
    end 	
  	resources :items
  	resources :comments
  end
  resources :categories 
  resources :users

  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title
			腰巴岔菜單
		%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
		%meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
		%link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css", :rel => "stylesheet"}/
		= csrf_meta_tags
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
		%script{:src => "//maps.google.com/maps/api/js?v=3.23&key=AIzaSyA9GUh4sWIfxMWQ7xdXShHKfgQ1adJbH8Q"}
		%script{:src => "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"}
		%script{:src => "//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js", :type => "text/javascript"}
		/ only if you need custom infoboxes

%body
	%nav.navbar.navbar-inverse.navbar-fixed-top
		.container
			.navbar-header
				%button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
					%span.sr-only Toggle navigation
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
				%a
					= link_to '腰巴岔菜單', root_path, class: "navbar-brand",:onclick => "window.location.reload()"

			/ Collect the nav links, forms, and other content for toggling
			#bs-example-navbar-collapse-1.collapse.navbar-collapse		
				%ul.nav.navbar-nav
					%li.dropdown
						%a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button", :style => "font-size:25px;"}
							餐廳分類
							%span.caret
						%ul.dropdown-menu{:role => "menu", :style => "font-size:25px;"}
							%li
								= link_to '全部餐廳', root_path
							- Category.all.each do |category|
								%li
									= link_to category.name, restaurants_path(category: category.name),:onclick => "window.location.reload()"
							%li
								- if user_signed_in?
									- if current_user.admin == true
										%li.divider{:role => "separator"}
										%li
											= link_to '新增/編輯分類', categories_path , style:'color:red;'

				/Search
				%ul.nav.navbar-nav.navbar-left
					%form.navbar-form.navbar-left.col-sm-6.col-sm-offset-3{:role => "search"}
						%div
							= form_tag @restaurant, method: :get do
								= text_field_tag :search, params[:search], placeholder: "Search...", class: "form-control"

				%ul.nav.navbar-nav.navbar-right
					- if user_signed_in?
						- if current_user.admin == true
							%li
								= link_to ' 新增餐廳', new_restaurant_path, class: "fa fa-file fa-2x"
							%li.dropdown
								%a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
									%i.fa.fa-angle-double-down.fa-2x{"aria-hidden" => "true"}
								%ul.dropdown-menu{:role => "menu"}
									- if current_user.admin == true
										%li
											= link_to ' User List', users_path, class: "fa fa-eye fa-2x"
										%li
											= link_to ' '+current_user.username, edit_user_registration_path, class: "fa fa-user fa-2x"
										%li
											= link_to ' Log out', destroy_user_session_path, :method => :delete, class: "fa fa-sign-out fa-2x"
					- else
						%li= link_to ' Sign up', new_user_registration_path, class: "fa fa-user-plus fa-2x"
						%li= link_to ' Log in', new_user_session_path, class: "fa fa-sign-in fa-2x"								


	- flash.each do |name, msg|
		= content_tag :div, msg, class: "alert alert-info"
	%br/
	%br/
	%br/
	= yield

	%footer#footer
		.inner
			%h2 Contact Me				
			#callouts
				.callout_inner
					.wrapper
						.callout
							%a{:href => "https://www.facebook.com/timing.chen"}
								%i.fa.fa-facebook-square.fa-3x{"aria-hidden" => "true"}
								%h4 Facebook
								/%p Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

						.callout
							%a{:href => "https://github.com/TimingJL/donggang_menu", :style => "text-decoration:none;"}
								%i.fa.fa-github.fa-3x{"aria-hidden" => "true"}
								%h4 Github
								/%p Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

						.callout
							%a{:href => "mailto:eefozeo@gmail.com", :style => "text-decoration:none;"}
								%i.fa.fa-envelope.fa-3x{"aria-hidden" => "true"}
								%h4 E-mail
								/%p Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.

		%h2 瀏覽人次
		%a
			%img{:alt => "", :border => "0", :src => "http://www.reliablecounter.com/count.php?page=glacial-dawn-23745.herokuapp.com/&digit=style/plain/1/&reloads=0", :title => ""}/
		%br/
		%a{:href => "http://www.fabbly.com", :style => "font-family: Geneva, Arial; font-size: 9px; color: #330010; text-decoration: none;", :target => "_blank"}